services:
  - type: web
    name: rail-reserve-app
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d7nhigjbc2fs738qav9g-a:5432/rail_reserve_db

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: rail_reserve_db2
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: rail_reserve_db2
          property: password
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: PORT
        value: "8080"
        healthCheckPath: /api