spring.application.name=TMSIR.App

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port = 5432
server.address=0.0.0.0
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.servlet.context-paths=/api
# Limits the number of connections Spring Boot keeps open
spring.datasource.hikari.maximum-pool-size=10