spring.application.name=TMSIR.App


spring.jpa.show-sql= true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
server.port=${PORT:8080}
spring.datasource.hikari.initialization-fail-timeout=60000

spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

spring.jpa.hibernate.ddl-auto=update

# Limits the number of connections Spring Boot keeps open
spring.datasource.hikari.maximum-pool-size=10