spring.application.name=TMSIR.App



# Brevo API Settings
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=railreservesupport1@gmail.com



# Strict connection timeouts so the thread doesn't hang foreverZ
spring.mail.properties.mail.smtp.connectiontimeout=2000
spring.mail.properties.mail.smtp.timeout=2000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.jpa.show-sql= true
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
server.port=${PORT:8080}
spring.datasource.hikari.initialization-fail-timeout=60000

spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

spring.jpa.hibernate.ddl-auto=update

# Limits the number of connections Spring Boot keeps open
spring.datasource.hikari.maximum-pool-size=10